contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - wolfi-baselayout
    - oauth2-proxy
    - ca-certificates-bundle

accounts:
  groups:
    - groupname: oauth2-proxy
      gid: 65532
  users:
    - username: oauth2-proxy
      uid: 65532
      gid: 65532
  run-as: oauth2-proxy

entrypoint:
  command: /bin/oauth2-proxy

archs:
  - x86_64
  - aarch64

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/oauth2-proxy
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/oauth2-proxy
