contents:
  packages:
    - kube-apiserver-1.28
    - kubernetes-1.28-default

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/kube-apiserver
