on:
  pull_request:
jobs:
  presubmit-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - run: go install github.com/chainguard-dev/yam@latest
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - run: yam --lint images/**/*.yaml
  presubmit-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - id: files
      uses: tj-actions/changed-files@ce810b29b28abf274afebdcd8fe47b8fba0f28bd # v35.9.0
      with:
        separator: ','
    - id: generate-matrix
      uses: ./.github/actions/generate-matrix
      with:
        modified-files: ${{ steps.files.outputs.all_changed_files }}
        melange-mode: none
  presubmit-build:
    runs-on: ubuntu-latest
    needs: presubmit-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Ensure image has tests
        if: matrix.testCommandExe == ''
        run: |
          echo "Error: ${{ matrix.imageName }} image is missing tests."
          exit 1
      - uses: ./.github/actions/build-image
        with: ${{ matrix }}
  presubmit-roundup:
    runs-on: ubuntu-latest
    needs: presubmit-build
    steps:
      - run: |
          echo "all matrix jobs completed"
